services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # app:
  #   build:
  #     context: ./src
  #     dockerfile: Dockerfile
  #   environment:
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_DATABASE: ${DB_DATABASE}
  #     DB_HOST: postgres
  #     REDIS_HOST: redis
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #     - redis
